### ISSUE TITLE
Market information refresh button not working

### ISSUE THREAD

**Issue by fiazk** [QuantumMechanics/NanoWallet#1]
Nothing happens when the refresh button is clicked. The information remains the same

**Comment by QuantumMechanics** [comment]
Nano get market information from coinmarketcap api that is updated every 5 minutes. 
It should work if you wait a bit and refresh

**Comment by QuantumMechanics** [comment]
Added a message at the bottom of the box to inform users

**Comment by fiazk** [comment]
Cool, because when clicked every 30 sec for example there was no update so a note would do. Thanks!
