### ISSUE TITLE
Namespace of level3 but is created not make the mosaic

### ISSUE THREAD

**Issue by GodTanu** [QuantumMechanics/NanoWallet#11]
Namespace is created of level3.
But mosaic can not make

ex :)
Namespace.SubNamespace.mosaic → can be created
Namespace.SubNamespace.SubNamespace → can be created (Bug?)
Namespace.SubNamespace.SubNamespace.mosaic → create impossible

NB2225-VL43PT-ZROTAE-IMVZFW-JK3CPE-7Y23OF-RTTO

**Comment by GodTanu** [comment]
I make Namespace ↓

・godtanu
・godtanu.tanugami
・godtanu.tanugami.tanusan

![1](https://cloud.githubusercontent.com/assets/20492223/19020318/6338c85e-88e0-11e6-930a-62be26da9d35.JPG)

![2](https://cloud.githubusercontent.com/assets/20492223/19020315/53d39f60-88e0-11e6-8d0c-a13d12d3db65.JPG)
![3](https://cloud.githubusercontent.com/assets/20492223/19020316/5c7b59e6-88e0-11e6-8fbb-4b6cc350e694.JPG)

**Comment by QuantumMechanics** [comment]
> Namespace.SubNamespace.SubNamespace → can be created (Bug?)

Namespaces are allowed to have up to 3 parts (3 maximum)

> Namespace.SubNamespace.SubNamespace.mosaic → create impossible

It was filtering third levels here, I don't know why. Also found that namespace module was not filtering.

Thanks, it is now fixed in 1.1.0

**Comment by GodTanu** [comment]
main.js
        // Exclude level 3 namespace
        this.isNotNamespaceLevel3 = function (elem) {
            return elem.fqn.split('.').length < 3;
        };

Change the following locations
  <= 3

It was to ensure that it works in this

**Comment by jabo38** [comment]
@GodTanu please post in your address

**Comment by GodTanu** [comment]
Thanks.
NB2225-VL43PT-ZROTAE-IMVZFW-JK3CPE-7Y23OF-RTTO

**Comment by jabo38** [comment]
Bounty paid. Tx hash: b84e39a487dcd0cae2f7a1bc4a82c5f6a2137f29d25545d55fa3e12a3d0072ba
