### ISSUE TITLE
Wallet is freeze . linefeed in message

### ISSUE THREAD

**Issue by GodTanu** [QuantumMechanics/NanoWallet#12]
freeze and put a line feed in the message.

line feed →
The message is broken → Wallet operation hang

line feed Code '0a' → `a 'It has been converted.
It has been converted

Ex:)
NCC
e38386e382b9e383880a5468697320697320746573742e

Nano
e38386e382b9e38388a5468697320697320746573742

line feed twice to →
Not hang because the number of characters is correct
But It has been amusing display.

![default](https://cloud.githubusercontent.com/assets/20492223/19046391/171456de-89d8-11e6-8c26-0b90cea6017e.JPG)

My Account
NB2225-VL43PT-ZROTAE-IMVZFW-JK3CPE-7Y23OF-RTTO
Sorry for my poor English.

**Comment by QuantumMechanics** [comment]
Hi, no worries I understood what you mean ;)

Your bug have been partially fixed in 1.1.0 because Lon already reported a bug with line-break in message. It is indeed the conversion that have a problem, I thought it was fixed...

Now it shows as "!" and not {{tx.message | fmtHexMessage}}

**Comment by GodTanu** [comment]
Thank you for checking.
We wait for Ver1.1.0 
And, we will continue with the verification.

**Comment by QuantumMechanics** [comment]
Should be fixed in 1.1.3 now: https://forum.nem.io/t/nano-wallet-beta-1-1-3-testnet-5-000-xem-bug-bounty/2791. Please let me know if it is not

**Comment by jabo38** [comment]
Bounty paid. Tx hash: b84e39a487dcd0cae2f7a1bc4a82c5f6a2137f29d25545d55fa3e12a3d0072ba
