### ISSUE TITLE
Cannot create an Apostille in Chrome.

### ISSUE THREAD

**Issue by SpiderBTT** [QuantumMechanics/NanoWallet#14]
**In Chrome** browser, during creating an Apostille, after pressing 'Send' we see the 'Transaction successfully sent' message, then the 'Processing' sign and it stays like that forever. The transaction is visible on the blockchain but the **.zip file is not created**.
It works in Firefox without a problem.

**Comment by QuantumMechanics** [comment]
It is working perfectly here in Chrome version 53.0.2785.143 (64-bit). Is your browser up to date or below the version I am using ?

**Comment by SpiderBTT** [comment]
I had the previous version of Chrome but after updating and restarting nothing changed. I'm not sure where's the problem, maybe someone else could test it too.

**Comment by QuantumMechanics** [comment]
Can you look at the console when "Processing" appears (tools -> JavaScript console) and report red error(s) here please ?

**Comment by SpiderBTT** [comment]
main.js:30304
 TypeError: Cannot read property 'push' of undefined
    at Object.updateNotaryData (main.js:110940)
    at _this2._Transactions.serializeAndAnnounceTransactionLoop.then._this2.common.privateKey (main.js:99757)
    at processQueue (main.js:32767)
    at main.js:32783
    at Scope.$eval (main.js:34066)
    at Scope.$digest (main.js:33879)
    at Scope.$apply (main.js:34174)
    at done (main.js:28215)
    at completeRequest (main.js:28417)
    at XMLHttpRequest.requestLoaded (main.js:28350)

**Comment by QuantumMechanics** [comment]
You probably have old Nty data loaded into your local storage. Please clean it and try again it should fix this issue.

**Comment by SpiderBTT** [comment]
I opened an incognito window and it worked there. So you are right, the issue was on my side. Thanks for help.

**Comment by QuantumMechanics** [comment]
I forgot to say that in the update.. As nty data structure changed a bit it'll cause error if there is already data in local storage. Going to post about that in forum.nem.io thread

**Comment by jabo38** [comment]
@SpiderBTT thanks for testing.  I had this bug too.   please paste in your address

**Comment by SpiderBTT** [comment]
Thanks, here's the address :)
NAIVE43D3SLI5MFIIXRFIY64RKOWIYQQQ6MBM2CC
