### ISSUE TITLE
Alias target can not  '_'&'-'  included Namespace 

### ISSUE THREAD

**Issue by GodTanu** [QuantumMechanics/NanoWallet#15]
Known Issues

please refer to
https://forum.nem.io/t/nano-wallet-beta-1-1-3-testnet-5-000-xem-bug-bounty/2791/34

**Comment by jabo38** [comment]
@GodTanu Please post you NEM address in here

**Comment by GodTanu** [comment]
Thanks.
NB2225-VL43PT-ZROTAE-IMVZFW-JK3CPE-7Y23OF-RTTO

**Comment by QuantumMechanics** [comment]
Fixed in 1.1.11
