### ISSUE TITLE
Removing cosigners "-1" input

### ISSUE THREAD

**Issue by fiazk** [QuantumMechanics/NanoWallet#2]
if you were to change the cosigners from 2 to 1 for example on the "Minimum signatures required", the app does not allow to input "1", for some reason you need to input "-1". I would say that "1" is more appropriate since the input asked is "Minimum signatures required". Using negative numbers could be confusing

**Comment by QuantumMechanics** [comment]
Will change the field name for "Signature changes" and maybe add explanations then. 
It is the number to add or remove from the current number of min signatures so in case of removal like above it is -1 signature

**Comment by QuantumMechanics** [comment]
Field name is "Minimum signatures changes" in edit multisignature contract and the placeholder says "Number of signatures to add (n) or remove (-n) - Automated removals". Will see if I can be more clear on that. But I'm wondering, app is not automatically setting it to -1 if you remove a cosignatory ?

**Comment by fiazk** [comment]
Yes, it does auto-fill it with "-1" only if you selected the m-sig account before. If you introduced the address to be removed it doesn't auto-fill. Don't you see the symbol "-" a little redundant if you already clicked on the red minus button. Also looks a bit weird to look at "Minimum signatures changes: -1"

**Comment by QuantumMechanics** [comment]
> Don't you see the symbol "-" a little redundant if you already clicked on the red minus button

Yes but for changes like:
- remove
- add
- add

If you type 1 there is no way to know if it is to add or remove a signature.
If it was one modification at the time I'd do it internally but not possible to know if multiple.

For the name of the field I just changed for "Relative change on minimum signatures", I'll see if someone have better ^^

**Comment by fiazk** [comment]
Got you :)
