### ISSUE TITLE
"Version: BETA 1.0.0"  |Question|

### ISSUE THREAD

**Issue by fiazk** [QuantumMechanics/NanoWallet#3]
![beta 1 0 0](https://cloud.githubusercontent.com/assets/17099341/18092411/7932ffc2-6ecc-11e6-909e-767eb648925c.png)
Do you also see this at the bottom right corner? it should be 1.0.1, no? or maybe there is an issue with my pc... not sure

**Comment by QuantumMechanics** [comment]
I just forgot to change that ^^ Fixed in version 1.0.2
