### ISSUE TITLE
Password to decrypt message

### ISSUE THREAD

**Issue by fiazk** [QuantumMechanics/NanoWallet#4]
It seems that when you send an encrypted message the other person cannot see it since the password asked is yours, shouldn't this be the other way around? Please see on the ss how I was able to decrypt my own message but not the one sent to me.
![encrypted msg password](https://cloud.githubusercontent.com/assets/17099341/18133773/3d0b40ce-6f9c-11e6-8ffe-b88d7dcacb4d.png)

**Comment by QuantumMechanics** [comment]
Yes it is a bug I just fixed. Was getting recipient public key instead of sender. Going to update thread on NEM forum with v1.0.6

**Comment by fiazk** [comment]
;) cool beans
