### ISSUE TITLE
Invalid Namespace id |Suggestion|

### ISSUE THREAD

**Issue by fiazk** [QuantumMechanics/NanoWallet#5]
Perhaps we could add something saying that spaces aren't allowed
![namespace error](https://cloud.githubusercontent.com/assets/17099341/18134760/cef0e0ea-6f9f-11e6-80f5-cd0a23955938.png)

**Comment by QuantumMechanics** [comment]
I'll add a function to check validity of namespace id. It'll show alerts and prevent send button to be activated if invalid.

**Comment by fiazk** [comment]
Nice

**Comment by fiazk** [comment]
also for the max number of character per namespace. The same for symbols such as "?"

**Comment by QuantumMechanics** [comment]
Sure ;). Improved in 1.0.10

**Comment by jabo38** [comment]
@fiazk please put in your address
