### ISSUE TITLE
Multiple Languages(Japanese)

### ISSUE THREAD

**Issue by GodTanu** [QuantumMechanics/NanoWallet#6]
Could you publish the source? I want to make pull request to correspond to Japanese.

**Comment by QuantumMechanics** [comment]
Sure, I'll push the languages module soon, I just need to update English translation file. 

Will let you know

**Comment by GodTanu** [comment]
Thanks English file update.
Japanese Nemster translate English to Japanese Now.
(sorry Poor English)
