### ISSUE TITLE
Apostille "keep private" isn't working

### ISSUE THREAD

**Issue by jabo38** [QuantumMechanics/NanoWallet#7]
when I try to check the keep private box, it stamps the file fine and I get the download, but then when I try to audit it, I get the message, "Verification failed, an error occured at signature verification !"

**Comment by SpiderBTT** [comment]
I did it twice with two different files and it worked. Could you try it again?

**Comment by QuantumMechanics** [comment]
Issue confirmed in 1.0.10, some private keys starts with "00" and they need a special fix that I forgot to apply. So in such cases the signature is invalid.
Fixed in upcoming 1.0.13

**Comment by jabo38** [comment]
confirmed fixed
