### ISSUE TITLE
can't cosign when multi-account create namespaces

### ISSUE THREAD

**Issue by kkooii** [QuantumMechanics/NanoWallet#9]
can't cosign when multi-account create namespaces

![co](https://cloud.githubusercontent.com/assets/8058411/18660022/d4ff3a26-7f40-11e6-8035-cf1d5e6dac7f.png)

**Comment by QuantumMechanics** [comment]
It was not receiving this kind of transactions in unconfirmed so it wasn't possible to sign them before.
Just finished to fix that on namespace provision, mosaic definition and supply change. 
Will be available in upcoming version.

**Comment by jabo38** [comment]
@kkooii please post in your address
